---
# Configuration sample file for Jingo (YAML)
application:
  title: 'F# Bootcamp'
  repository: './'
  docSubdir: ''
  remote: ''
  pushInterval: 30
  secret: change me
  git: git
  skipGitCheck: false
  loggingMode: 1
  pedanticMarkdown: true
  gfmBreaks: true
  staticWhitelist: '/\.png$/i, /\.jpg$/i, /\.gif$/i'
  proxyPath: ''
authentication:
  google:
    enabled: false
    clientId: replace me with the real value
    clientSecret: replace me with the real value
    redirectURL: ''
  github:
    enabled: false
    clientId: replace me with the real value
    clientSecret: replace me with the real value
    redirectURL: ''
  local:
    enabled: true
    accounts:
      - username: 'danielepo'
        passwordHash: '3aae2b8542815a77fc1473f4a56e9bbceaf913ac'
        email: ''
features:
  markitup: false
  codemirror: true
server:
  hostname: localhost
  port: 6067
  localOnly: false
  baseUrl: ''
  CORS:
    enabled: false
    allowedOrigin: '*'
authorization:
  anonRead: true
  validMatches: .+
  emptyEmailMatches: false
pages:
  index: Home
  title:
    fromFilename: true
    fromContent: false
    asciiOnly: false
    lowercase: false
  itemsPerPage: 10
customizations:
  sidebar: _sidebar.md
  footer: _footer.md
  style: _style.css
  script: _script.js

